apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
spec:
  replicas: 1
  selector:
    matchLabels: { app: api-gateway }
  template:
    metadata:
      labels: { app: api-gateway }
    spec:
      initContainers:
        - name: wait-for-services
          image: busybox:1.28
          command:
            - 'sh'
            - '-c'
            - >
              until nc -z user-manager 5003; do echo waiting for user-manager; sleep 2; done;
              until nc -z data-collector 5002; do echo waiting for data-collector; sleep 2; done;
      containers:
        - name: api-gateway
          image: api-gateway:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
          livenessProbe:
            tcpSocket:
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway-service
spec:
  type: NodePort
  selector:
    app: api-gateway
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30080