apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
stringData:
  # Data DB Secrets
  DATA_DB_ROOT_PASSWORD: "data_root_pwd"
  DATA_DB_USER: "data_user"
  DATA_DB_PASSWORD: "data_app_pwd"
  # User DB Secrets
  USER_DB_ROOT_PASSWORD: "user_root_pwd"
  USER_DB_USER: "user"
  USER_DB_PASSWORD: "user_app_pwd"
  # Credentials
  OPEN_SKY_CLIENT_ID: "elenamonticchio-api-client"
  OPEN_SKY_CLIENT_SECRET: "t23IEaB7UZMJGHMwWK96BQBGXyGO2sPz"
  SMTP_USER: "piersaia01@gmail.com"
  SMTP_PASS: "ndbmkoekgzjwngje"
  MAIL_FROM: "piersaia01@gmail.com"
