apiVersion: v1
kind: Service
metadata:
  name: user-db
spec:
  ports:
    - port: 3306
  selector:
    app: user-db
  clusterIP: None
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: user-db
spec:
  serviceName: "user-db"
  replicas: 1
  selector:
    matchLabels:
      app: user-db
  template:
    metadata:
      labels:
        app: user-db
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          imagePullPolicy: IfNotPresent
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom: { secretKeyRef: { name: app-secrets, key: USER_DB_ROOT_PASSWORD } }
            - name: MYSQL_DATABASE
              valueFrom: { configMapKeyRef: { name: app-config, key: USER_DB_NAME } }
            - name: MYSQL_USER
              valueFrom: { secretKeyRef: { name: app-secrets, key: USER_DB_USER } }
            - name: MYSQL_PASSWORD
              valueFrom: { secretKeyRef: { name: app-secrets, key: USER_DB_PASSWORD } }
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-storage
              mountPath: /var/lib/mysql
  volumeClaimTemplates:
    - metadata:
        name: mysql-storage
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: data-db
spec:
  ports:
    - port: 3306
  selector:
    app: data-db
  clusterIP: None
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: data-db
spec:
  serviceName: "data-db"
  replicas: 1
  selector:
    matchLabels:
      app: data-db
  template:
    metadata:
      labels:
        app: data-db
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          imagePullPolicy: IfNotPresent
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom: { secretKeyRef: { name: app-secrets, key: DATA_DB_ROOT_PASSWORD } }
            - name: MYSQL_DATABASE
              valueFrom: { configMapKeyRef: { name: app-config, key: DATA_DB_NAME } }
            - name: MYSQL_USER
              valueFrom: { secretKeyRef: { name: app-secrets, key: DATA_DB_USER } }
            - name: MYSQL_PASSWORD
              valueFrom: { secretKeyRef: { name: app-secrets, key: DATA_DB_PASSWORD } }
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-storage
              mountPath: /var/lib/mysql
  volumeClaimTemplates:
    - metadata:
        name: mysql-storage
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi