apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-collector
spec:
  replicas: 1
  selector:
    matchLabels: { app: data-collector }
  template:
    metadata:
      labels: { app: data-collector, monitor: prometheus }
    spec:
      initContainers:
        - name: wait-for-dependencies
          image: busybox:1.28
          command:
            - 'sh'
            - '-c'
            - >
              until nc -z data-db 3306; do echo waiting for data-db; sleep 2; done;
              until nc -z kafka 9092; do echo waiting for kafka; sleep 2; done;
              until nc -z user-manager 50051; do echo waiting for user-manager grpc; sleep 2; done;
      containers:
        - name: data-collector
          image: data-collector:latest
          imagePullPolicy: Never
          envFrom:
            - configMapRef: { name: app-config }
          env:
            - name: DB_HOST
              valueFrom: { configMapKeyRef: { name: app-config, key: DATA_COL_DB_HOST } }
            - name: DB_PASSWORD
              valueFrom: { secretKeyRef: { name: app-secrets, key: DATA_DB_PASSWORD } }
            - name: OPEN_SKY_CLIENT_ID
              valueFrom: { secretKeyRef: { name: app-secrets, key: OPEN_SKY_CLIENT_ID } }
            - name: OPEN_SKY_CLIENT_SECRET
              valueFrom: { secretKeyRef: { name: app-secrets, key: OPEN_SKY_CLIENT_SECRET } }
            - name: NODE_NAME
              valueFrom: { fieldRef: { fieldPath: spec.nodeName } }
          ports:
            - containerPort: 5002
            - containerPort: 9991
          livenessProbe:
            httpGet:
              path: /health
              port: 5002
            initialDelaySeconds: 15
            periodSeconds: 10
          readinessProbe:
              httpGet:
                path: /health
                port: 5002
              initialDelaySeconds: 10
              periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: data-collector
spec:
  selector: { app: data-collector }
  ports:
    - name: http
      port: 5002
      targetPort: 5002
    - name: metrics
      port: 9991
      targetPort: 9991