apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-manager
spec:
  replicas: 1
  selector:
    matchLabels: { app: user-manager }
  template:
    metadata:
      labels: { app: user-manager, monitor: prometheus }
      annotations:
          prometheus.io/scrape: "true"
          prometheus.io/port: "9992"
          prometheus.io/path: "/metrics"
    spec:
      initContainers:
        - name: wait-for-user-db
          image: busybox:1.28
          command: [ 'sh', '-c', "until nc -z user-db 3306; do echo waiting for user-db; sleep 2; done" ]
      containers:
        - name: user-manager
          image: user-manager:latest
          imagePullPolicy: Never
          envFrom:
            - configMapRef: { name: app-config }
          env:
            - name: DB_HOST
              valueFrom: { configMapKeyRef: { name: app-config, key: USER_MGR_DB_HOST } }
            - name: DB_PASSWORD
              valueFrom: { secretKeyRef: { name: app-secrets, key: USER_DB_PASSWORD } }
            - name: NODE_NAME
              valueFrom: { fieldRef: { fieldPath: spec.nodeName } }
          ports:
            - containerPort: 5003
            - containerPort: 50051
            - containerPort: 9992
          livenessProbe:
            httpGet:
              path: /health
              port: 5003
            initialDelaySeconds: 15
            periodSeconds: 10
          readinessProbe:
              httpGet:
                path: /health
                port: 5003
              initialDelaySeconds: 10
              periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: user-manager
spec:
  selector: { app: user-manager }
  ports:
    - name: http
      port: 5003
      targetPort: 5003
    - name: grpc
      port: 50051
      targetPort: 50051
    - name: metrics
      port: 9992
      targetPort: 9992